name: "Update lock weekly"

on:
  push:
    paths:
      - '.github/workflows/update.yml'
  schedule:
    - cron:  '19 18 * * 2'
  repository_dispatch:
  workflow_dispatch:
    inputs:
      update_lock:
        description: Update flake.lock
        required: true
        default: true
        type: boolean
      skip_check:
        description: Skip evaluation
        required: true
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  bump_lock:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    outputs:
      packages: ${{ steps.pkgs.outputs.packages }}

    steps:
    - name: 0-1. Checkout repository
      uses: actions/checkout@v4

    - name: 0-2. Install Nix
      uses: nixbuild/nix-quick-install-action@v30

    - name: 1-1. Update flake.lock
      if: ${{ inputs.update_lock == true || github.event_name != 'workflow_dispatch' }}
      run: nix flake update

    - name: 2-1. Show flake metadata
      id: pkgs
      if: ${{ always() }}
      run: |
        nix flake metadata
        echo "packages=`nix eval --json .#packages.x86_64-linux --apply 'builtins.attrNames'`" >> $GITHUB_OUTPUT

    - name: 2-2. Show flake information
      if: ${{ always() }}
      run: nix flake show

    - name: 2-3. Check evaluation
      if: ${{ inputs.skip_check == false || github.event_name != 'workflow_dispatch' }}
      run: nix flake check --no-build --no-allow-import-from-derivation

    - name: 3-1. Bump flake.lock
      if: ${{ inputs.update_lock == true || github.event_name != 'workflow_dispatch' }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update: flake.lock"
        file_pattern: "flake.lock"

  build:
    needs: bump_lock
    secrets: inherit
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.bump_lock.outputs.packages) }}
    uses: ./.github/workflows/build.yml
    with:
      package: ${{ matrix.package }}
